# Generated by Django 3.0.5 on 2025-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_exammonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammonitoring',
            name='mobile_violation_occurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exammonitoring',
            name='multiple_students_violation_occurred',
            field=models.BooleanField(default=False),
        ),
    ]
