# Generated by Django 3.0.5 on 2025-04-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20250226_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_limit',
            field=models.PositiveIntegerField(default=60, help_text='Time limit in minutes'),
        ),
    ]
